version: '3,8'

services:

  db:
    image: postgres
    container_name: whoami
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_USER: whoami
      POSTGRES_PASSWORD: whoami
      POSTGRES_DB: whoami
    ports:
      - "5432:5432"
